server:
  servlet:
    context-path: /jiajuxiaoshouxitong
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/xiaoshoxitong?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    password: 123654
  mvc:
    view:
      prefix: /
      suffix: .jsp
    static-path-pattern: /**

mybatis:
  mapper-locations: classpath:com/mapper/*.xml
